// Code generated by mockery. DO NOT EDIT.

package main

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockQueueTrigger is an autogenerated mock type for the QueueTrigger type
type MockQueueTrigger struct {
	mock.Mock
}

type MockQueueTrigger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueueTrigger) EXPECT() *MockQueueTrigger_Expecter {
	return &MockQueueTrigger_Expecter{mock: &_m.Mock}
}

// TriggerProcessing provides a mock function with given fields: ctx
func (_m *MockQueueTrigger) TriggerProcessing(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TriggerProcessing")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueueTrigger_TriggerProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TriggerProcessing'
type MockQueueTrigger_TriggerProcessing_Call struct {
	*mock.Call
}

// TriggerProcessing is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQueueTrigger_Expecter) TriggerProcessing(ctx interface{}) *MockQueueTrigger_TriggerProcessing_Call {
	return &MockQueueTrigger_TriggerProcessing_Call{Call: _e.mock.On("TriggerProcessing", ctx)}
}

func (_c *MockQueueTrigger_TriggerProcessing_Call) Run(run func(ctx context.Context)) *MockQueueTrigger_TriggerProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQueueTrigger_TriggerProcessing_Call) Return(_a0 error) *MockQueueTrigger_TriggerProcessing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueueTrigger_TriggerProcessing_Call) RunAndReturn(run func(context.Context) error) *MockQueueTrigger_TriggerProcessing_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueueTrigger creates a new instance of MockQueueTrigger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueueTrigger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueueTrigger {
	mock := &MockQueueTrigger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
